// State management and DOM element references

export const dom = {
  app: document.querySelector(".app"),
  titlebar: document.getElementById("titlebar"),
  windowMinimize: document.getElementById("window-minimize"),
  windowMaximize: document.getElementById("window-maximize"),
  windowClose: document.getElementById("window-close"),
  navButtons: document.querySelectorAll(".nav-btn"),
  viewCreate: document.getElementById("view-create"),
  viewModify: document.getElementById("view-modify"),
  viewProfiles: document.getElementById("view-profiles"),
  viewAbout: document.getElementById("view-about"),
  statusLine: document.getElementById("status-line"),
  footMeta: document.getElementById("foot-meta"),
  statusPill: document.getElementById("status-pill"),
  logoutBtn: document.getElementById("logout-btn"),
  toast: document.getElementById("toast"),
  loginOverlay: document.getElementById("login-overlay"),
  loginClose: document.getElementById("login-close"),
  languageOverlay: document.getElementById("language-overlay"),
  languageSetupList: document.getElementById("language-setup-list"),
  languageSetupContinue: document.getElementById("language-setup-continue"),
  loginForm: document.getElementById("login-form"),
  loginUsername: document.getElementById("login-username"),
  loginPassword: document.getElementById("login-password"),
  twoFactorOverlay: document.getElementById("twofactor-overlay"),
  twoFactorForm: document.getElementById("twofactor-form"),
  twoFactorCode: document.getElementById("twofactor-code"),
  aboutVersion: document.getElementById("about-version"),
  aboutDataDir: document.getElementById("about-data-dir"),
  aboutSession: document.getElementById("about-session"),
  githubLink: document.getElementById("github-link"),
  settingsTheme: document.getElementById("settings-theme"),
  themeGrid: document.getElementById("theme-color-grid"),
  themePresetName: document.getElementById("theme-preset-name"),
  themePresetSave: document.getElementById("theme-preset-save"),
  themePresetDelete: document.getElementById("theme-preset-delete"),
  themePresetImport: document.getElementById("theme-preset-import"),
  themePresetExport: document.getElementById("theme-preset-export"),
  themeReset: document.getElementById("theme-reset"),
  themeOpen: document.getElementById("theme-open"),
  themeOverlay: document.getElementById("theme-overlay"),
  themeOverlayClose: document.getElementById("theme-overlay-close"),
  galleryOverlay: document.getElementById("gallery-overlay"),
  galleryClose: document.getElementById("gallery-close"),
  galleryRefresh: document.getElementById("gallery-refresh"),
  galleryUpload: document.getElementById("gallery-upload"),
  galleryList: document.getElementById("gallery-list"),
  galleryLoadMore: document.getElementById("gallery-load-more"),
  galleryCancel: document.getElementById("gallery-cancel"),
  galleryUse: document.getElementById("gallery-use"),
  conflictOverlay: document.getElementById("conflict-overlay"),
  conflictMessage: document.getElementById("conflict-message"),
  conflictChangeTime: document.getElementById("conflict-change-time"),
  conflictContinue: document.getElementById("conflict-continue"),
  trayPromptOverlay: document.getElementById("tray-prompt-overlay"),
  trayPromptYes: document.getElementById("tray-prompt-yes"),
  trayPromptNo: document.getElementById("tray-prompt-no"),
  settingsChangeDir: document.getElementById("settings-change-dir"),
  settingsOpenDir: document.getElementById("settings-open-dir"),
  settingsLanguage: document.getElementById("settings-language"),
  languageSelect: document.getElementById("language-select"),
  languageTrigger: document.getElementById("language-trigger"),
  languageMenu: document.getElementById("language-menu"),
  languageLabel: document.getElementById("language-label"),
  languageFlag: document.getElementById("language-flag"),
  eventGroup: document.getElementById("event-group"),
  eventProfile: document.getElementById("event-profile"),
  eventProfileClear: document.getElementById("event-profile-clear"),
  eventTimezone: document.getElementById("event-timezone"),
  eventDuration: document.getElementById("event-duration"),
  eventDurationPreview: document.getElementById("event-duration-preview"),
  eventDateSource: document.getElementById("event-date-source"),
  eventDateOption: document.getElementById("event-date-option"),
  eventPatternDates: document.getElementById("event-pattern-dates"),
  eventManualFields: document.getElementById("event-manual-fields"),
  eventManualDate: document.getElementById("event-manual-date"),
  eventManualTime: document.getElementById("event-manual-time"),
  eventDateHint: document.getElementById("event-date-hint"),
  eventName: document.getElementById("event-name"),
  eventDescription: document.getElementById("event-description"),
  eventCategory: document.getElementById("event-category"),
  eventTagsInput: document.getElementById("event-tags-input"),
  eventTagsChips: document.getElementById("event-tags-chips"),
  eventTags: document.getElementById("event-tags"),
  eventAccess: document.getElementById("event-access"),
  eventRoleRestrictions: document.getElementById("event-role-restrictions"),
  eventRoleList: document.getElementById("event-role-list"),
  eventImageId: document.getElementById("event-image-id"),
  eventImagePicker: document.getElementById("event-image-picker"),
  eventSendNotification: document.getElementById("event-send-notification"),
  eventFeatured: document.getElementById("event-featured"),
  eventFeaturedField: document.getElementById("event-featured-field"),
  eventGroupFair: document.getElementById("event-group-fair"),
  eventGroupFairField: document.getElementById("event-group-fair-field"),
  eventLanguageFilter: document.getElementById("event-language-filter"),
  eventLanguageList: document.getElementById("event-language-list"),
  eventLanguageHint: document.getElementById("event-language-hint"),
  eventPlatformList: document.getElementById("event-platform-list"),
  eventCreate: document.getElementById("event-create"),
  eventImportJson: document.getElementById("event-import-json"),
  eventAdvancedSection: document.getElementById("event-advanced-section"),
  eventExportJson: document.getElementById("event-export-json"),
  eventExportSection: document.getElementById("event-export-section"),
  eventBack: document.getElementById("event-back"),
  eventNext: document.getElementById("event-next"),
  eventLimitNotice: document.getElementById("event-limit-notice"),
  eventUpcomingCount: document.getElementById("event-upcoming-count"),
  eventCountRefresh: document.getElementById("event-count-refresh"),
  eventWarnConflicts: document.getElementById("event-warn-conflicts"),
  modifyGroup: document.getElementById("modify-group"),
  modifyRefresh: document.getElementById("modify-refresh"),
  modifyShowPending: document.getElementById("modify-show-pending"),
  modifyEventGrid: document.getElementById("modify-event-grid"),
  modifyCount: document.getElementById("modify-count"),
  modifyOverlay: document.getElementById("modify-overlay"),
  modifyClose: document.getElementById("modify-close"),
  modifyCancel: document.getElementById("modify-cancel"),
  modifySave: document.getElementById("modify-save"),
  modifyProfile: document.getElementById("modify-profile"),
  modifyProfileLoad: document.getElementById("modify-profile-load"),
  modifyEventName: document.getElementById("modify-event-name"),
  modifyEventDescription: document.getElementById("modify-event-description"),
  modifyEventCategory: document.getElementById("modify-event-category"),
  modifyTagsInput: document.getElementById("modify-tags-input"),
  modifyTagsChips: document.getElementById("modify-tags-chips"),
  modifyEventTags: document.getElementById("modify-event-tags"),
  modifyEventAccess: document.getElementById("modify-event-access"),
  modifyRoleRestrictions: document.getElementById("modify-role-restrictions"),
  modifyRoleList: document.getElementById("modify-role-list"),
  modifyEventImageId: document.getElementById("modify-event-image-id"),
  modifyEventImagePicker: document.getElementById("modify-event-image-picker"),
  modifyEventDate: document.getElementById("modify-event-date"),
  modifyEventTime: document.getElementById("modify-event-time"),
  modifyEventTimezone: document.getElementById("modify-event-timezone"),
  modifyEventDuration: document.getElementById("modify-event-duration"),
  modifyEventDurationPreview: document.getElementById("modify-event-duration-preview"),
  modifyLanguageFilter: document.getElementById("modify-language-filter"),
  modifyLanguageList: document.getElementById("modify-language-list"),
  modifyLanguageHint: document.getElementById("modify-language-hint"),
  modifyPlatformList: document.getElementById("modify-platform-list"),
  modifyFeatured: document.getElementById("modify-featured"),
  modifyFeaturedField: document.getElementById("modify-featured-field"),
  modifyGroupFair: document.getElementById("modify-group-fair"),
  modifyGroupFairField: document.getElementById("modify-group-fair-field"),
  profileExisting: document.getElementById("profile-existing"),
  profileNew: document.getElementById("profile-new"),
  profileEdit: document.getElementById("profile-edit"),
  profileDelete: document.getElementById("profile-delete"),
  profileGroup: document.getElementById("profile-group"),
  profileDisplayName: document.getElementById("profile-display-name"),
  profileName: document.getElementById("profile-name"),
  profileDescription: document.getElementById("profile-description"),
  profileCategory: document.getElementById("profile-category"),
  profileTagsInput: document.getElementById("profile-tags-input"),
  profileTagsChips: document.getElementById("profile-tags-chips"),
  profileTags: document.getElementById("profile-tags"),
  profileAccess: document.getElementById("profile-access"),
  profileRoleRestrictions: document.getElementById("profile-role-restrictions"),
  profileRoleList: document.getElementById("profile-role-list"),
  profileImageId: document.getElementById("profile-image-id"),
  profileImagePicker: document.getElementById("profile-image-picker"),
  profileDuration: document.getElementById("profile-duration"),
  profileDurationPreview: document.getElementById("profile-duration-preview"),
  profileTimezone: document.getElementById("profile-timezone"),
  profileDateMode: document.getElementById("profile-date-mode"),
  profileSendNotification: document.getElementById("profile-send-notification"),
  profileFeatured: document.getElementById("profile-featured"),
  profileFeaturedField: document.getElementById("profile-featured-field"),
  profileGroupFair: document.getElementById("profile-group-fair"),
  profileGroupFairField: document.getElementById("profile-group-fair-field"),
  profileImportExportButtons: document.getElementById("profile-import-export-buttons"),
  profileImportJson: document.getElementById("profile-import-json"),
  profileExportJson: document.getElementById("profile-export-json"),
  settingsMinimizeTray: document.getElementById("settings-minimize-tray"),
  settingsStartOnStartup: document.getElementById("settings-start-on-startup"),
  settingsShowFeaturedVerification: document.getElementById("settings-show-featured-verification"),
  featuredVerificationCard: document.getElementById("featured-verification-card"),
  settingsEnableAdvanced: document.getElementById("settings-enable-advanced"),
  settingsAdvancedCaret: document.getElementById("settings-advanced-caret"),
  settingsAdvancedOptions: document.getElementById("settings-advanced-options"),
  settingsEnableImportExport: document.getElementById("settings-enable-import-export"),
  settingsAutoUploadImages: document.getElementById("settings-auto-upload-images"),
  settingsSave: document.getElementById("settings-save"),
  featuredVerifyGroup: document.getElementById("featured-verify-group"),
  featuredVerifyBtn: document.getElementById("featured-verify-btn"),
  featuredVerifiedList: document.getElementById("featured-verified-list"),
  profileLanguageFilter: document.getElementById("profile-language-filter"),
  profileLanguageList: document.getElementById("profile-language-list"),
  profileLanguageHint: document.getElementById("profile-language-hint"),
  profilePlatformList: document.getElementById("profile-platform-list"),
  patternList: document.getElementById("pattern-list"),
  patternType: document.getElementById("pattern-type"),
  patternWeekday: document.getElementById("pattern-weekday"),
  patternWeekdayField: document.getElementById("pattern-weekday-field"),
  patternDateField: document.getElementById("pattern-date-field"),
  patternMonth: document.getElementById("pattern-month"),
  patternDay: document.getElementById("pattern-day"),
  patternDatePreview: document.getElementById("pattern-date-preview"),
  patternTime: document.getElementById("pattern-time"),
  patternAdd: document.getElementById("pattern-add"),
  patternClear: document.getElementById("pattern-clear"),
  profileSave: document.getElementById("profile-save"),
  profileBack: document.getElementById("profile-back"),
  profileNext: document.getElementById("profile-next"),
  // Automation elements
  automationCard: document.getElementById("automation-card"),
  automationEnabled: document.getElementById("automation-enabled"),
  automationSettings: document.getElementById("automation-settings"),
  automationTimingMode: document.getElementById("automation-timing-mode"),
  automationOffsetSettings: document.getElementById("automation-offset-settings"),
  automationTimingInput: document.getElementById("automation-timing-input"),
  automationOffsetProse: document.getElementById("automation-offset-prose"),
  automationMonthlyProse: document.getElementById("automation-monthly-prose"),
  automationMonthlySettings: document.getElementById("automation-monthly-settings"),
  automationMonthlyDay: document.getElementById("automation-monthly-day"),
  automationMonthlyTime: document.getElementById("automation-monthly-time"),
  automationRepeatMode: document.getElementById("automation-repeat-mode"),
  automationRepeatCountField: document.getElementById("automation-repeat-count-field"),
  automationRepeatCount: document.getElementById("automation-repeat-count"),
  automationRestore: document.getElementById("automation-restore"),
  automationRestoreCount: document.getElementById("automation-restore-count"),
  // Automation confirm overlay
  automationConfirmOverlay: document.getElementById("automation-confirm-overlay"),
  automationConfirmOk: document.getElementById("automation-confirm-ok"),
  automationConfirmCancel: document.getElementById("automation-confirm-cancel"),
  // Discord elements
  settingsDiscordEnabled: document.getElementById("settings-discord-enabled"),
  discordSettingsCaret: document.getElementById("discord-settings-caret"),
  discordSettingsPanel: document.getElementById("discord-settings-panel"),
  discordGroupSelect: document.getElementById("discord-group-select"),
  discordGroupConfig: document.getElementById("discord-group-config"),
  discordBotToken: document.getElementById("discord-bot-token"),
  discordTokenToggle: document.getElementById("discord-token-toggle"),
  discordGuildId: document.getElementById("discord-guild-id"),
  discordTestBtn: document.getElementById("discord-test-btn"),
  discordTestResult: document.getElementById("discord-test-result"),
  discordSaveBtn: document.getElementById("discord-save-btn"),
  discordConfiguredList: document.getElementById("discord-configured-list"),
  discordSyncField: document.getElementById("discord-sync-field"),
  discordSyncCheck: document.getElementById("discord-sync-check"),
  eventDiscordSyncField: document.getElementById("event-discord-sync-field"),
  eventDiscordSyncCheck: document.getElementById("event-discord-sync-check"),
  // Webhook post toggles
  webhookPostField: document.getElementById("webhook-post-field"),
  webhookPostCheck: document.getElementById("webhook-post-check"),
  eventWebhookPostField: document.getElementById("event-webhook-post-field"),
  eventWebhookPostCheck: document.getElementById("event-webhook-post-check"),
  // Calendar / Webhook elements
  settingsCalendarEnabled: document.getElementById("settings-calendar-enabled"),
  calendarSaveDirMeta: document.getElementById("calendar-save-dir-meta"),
  calendarSaveDirDisplay: document.getElementById("calendar-save-dir-display"),
  calendarSaveDirBtn: document.getElementById("calendar-save-dir-btn"),
  calendarSaveDirOpen: document.getElementById("calendar-save-dir-open"),
  calendarSyncField: document.getElementById("calendar-sync-field"),
  calendarSyncCheck: document.getElementById("calendar-sync-check"),
  // Profile calendar reminders (Schedule step)
  profileCalendarRemindersCard: document.getElementById("profile-calendar-reminders-card"),
  profileCalendarRemindersEnabled: document.getElementById("profile-calendar-reminders-enabled"),
  profileCalendarRemindersList: document.getElementById("profile-calendar-reminders-list"),
  profileCalendarReminderAdd: document.getElementById("profile-calendar-reminder-add"),
  profileCalendarRemindersHint: document.getElementById("profile-calendar-reminders-hint"),
  // Event calendar options (Date step)
  eventCalendarCreateField: document.getElementById("event-calendar-create-field"),
  eventCalendarCreateCheck: document.getElementById("event-calendar-create-check"),
  eventCalendarRemindersEnabledField: document.getElementById("event-calendar-reminders-enabled-field"),
  eventCalendarRemindersEnabled: document.getElementById("event-calendar-reminders-enabled"),
  eventCalendarRemindersList: document.getElementById("event-calendar-reminders-list"),
  eventCalendarReminderAdd: document.getElementById("event-calendar-reminder-add"),
  eventCalendarRemindersHint: document.getElementById("event-calendar-reminders-hint"),
  // Webhook elements (inside discord-group-config)
  discordWebhookField: document.getElementById("discord-webhook-field"),
  discordWebhookEnabledCheck: document.getElementById("discord-webhook-enabled"),
  discordWebhookUrlField: document.getElementById("discord-webhook-url-field"),
  discordWebhookUrl: document.getElementById("discord-webhook-url"),
  discordWebhookToggle: document.getElementById("discord-webhook-toggle"),
  discordWebhookTestBtn: document.getElementById("discord-webhook-test-btn"),
  // EC Kit elements
  eckitImportBtn: document.getElementById("eckit-import-btn"),
  eckitConfig: document.getElementById("eckit-config"),
  eckitStatus: document.getElementById("eckit-status"),
  eckitWebhookName: document.getElementById("eckit-webhook-name"),
  eckitEmbedColor: document.getElementById("eckit-embed-color"),
  eckitEmbedColorHex: document.getElementById("eckit-embed-color-hex"),
  eckitAvatarUrl: document.getElementById("eckit-avatar-url"),
  // Profile webhook message (Basics tab, kit-unlocked)
  profileWebhookMessageField: document.getElementById("profile-webhook-message-field"),
  profileWebhookMessageEnabled: document.getElementById("profile-webhook-message-enabled"),
  profileWebhookMessageCard: document.getElementById("profile-webhook-message-card"),
  profileWebhookMessage: document.getElementById("profile-webhook-message"),
  profileWebhookImagePath: document.getElementById("profile-webhook-image-path"),
  profileWebhookImageBtn: document.getElementById("profile-webhook-image-btn"),
  // Event webhook message (Details step, kit-unlocked)
  eventWebhookMessageField: document.getElementById("event-webhook-message-field"),
  eventWebhookMessageEnabled: document.getElementById("event-webhook-message-enabled"),
  eventWebhookMessageInput: document.getElementById("event-webhook-message-input"),
  eventWebhookMessage: document.getElementById("event-webhook-message"),
  eventWebhookImagePath: document.getElementById("event-webhook-image-path"),
  eventWebhookImageBtn: document.getElementById("event-webhook-image-btn"),
  // Modify modal posting options (pending events only)
  modifyPostingOptions: document.getElementById("modify-posting-options"),
  modifyDiscordSyncField: document.getElementById("modify-discord-sync-field"),
  modifyDiscordSync: document.getElementById("modify-discord-sync"),
  modifyWebhookPostField: document.getElementById("modify-webhook-post-field"),
  modifyWebhookPost: document.getElementById("modify-webhook-post"),
  modifyCalendarSyncField: document.getElementById("modify-calendar-sync-field"),
  modifyCalendarSync: document.getElementById("modify-calendar-sync"),
  modifyCalendarRemindersEnabledField: document.getElementById("modify-calendar-reminders-enabled-field"),
  modifyCalendarRemindersEnabled: document.getElementById("modify-calendar-reminders-enabled"),
  modifyCalendarRemindersList: document.getElementById("modify-calendar-reminders-list"),
  modifyCalendarReminderAdd: document.getElementById("modify-calendar-reminder-add"),
  modifyCalendarRemindersHint: document.getElementById("modify-calendar-reminders-hint"),
  modifyWebhookMessageSection: document.getElementById("modify-webhook-message-section"),
  modifyWebhookMessageEnabled: document.getElementById("modify-webhook-message-enabled"),
  modifyWebhookMessageInput: document.getElementById("modify-webhook-message-input"),
  modifyWebhookMessage: document.getElementById("modify-webhook-message"),
  modifyWebhookImagePath: document.getElementById("modify-webhook-image-path"),
  modifyWebhookImageBtn: document.getElementById("modify-webhook-image-btn")
};

export const state = {
  app: {
    updateAvailable: false,
    rateLimits: {}
  },
  session: {},
  settings: {},
  user: null,
  groups: [],
  groupRoles: {},
  kitGroupIds: [],
  profiles: {},
  event: {
    languages: [],
    platforms: [],
    profile: null,
    selectedGroupId: null,
    selectedProfileKey: null,
    dateOptions: [],
    dateSource: "manual",
    upcomingCount: null,
    upcomingLimit: 10,
    hourlyCreateHistory: {},
    hourlyLimitUntil: {},
    createdEventIds: {},
    serverHourlyCount: 0,
    backoffIndex: 0,
    createBlocked: false,
    createInProgress: false,
    tagInput: null,
    roleIds: []
  },
  modify: {
    events: [],
    pendingEvents: [],
    optimisticEvents: new Map(),
    selectedGroupId: null,
    selectedEvent: null,
    selectedPendingEvent: null,
    languages: [],
    platforms: [],
    roleIds: [],
    tagInput: null,
    loading: false,
    saving: false,
    pendingDeletions: new Set(),
    pendingPostNow: new Set(),
    deletedTombstones: new Map(),
    refreshBackoffUntil: 0,
    refreshBackoffIndex: 0,
    lastRefreshTime: 0,
    showPending: true,
    missedCount: 0,
    selectedImageUrl: ""
  },
  profile: {
    mode: "create",
    currentKey: null,
    languages: ["eng"],
    platforms: ["standalonewindows", "android"],
    roleIds: [],
    patterns: [],
    tagInput: null
  },
  gallery: {
    files: [],
    selectedId: null,
    targetInput: null,
    offset: 0,
    hasMore: false,
    loading: false
  }
};

// Wizard state (referenced by both events and profiles)
export let eventWizard = null;
export let profileWizard = null;
export let profileEditConfirmed = false;

export function setEventWizard(wizard) {
  eventWizard = wizard;
}

export function setProfileWizard(wizard) {
  profileWizard = wizard;
}

export function setProfileEditConfirmed(value) {
  profileEditConfirmed = value;
}

export function getEventWizard() {
  return eventWizard;
}

export function getProfileWizard() {
  return profileWizard;
}

export function getProfileEditConfirmed() {
  return profileEditConfirmed;
}
